apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ggfwyekm0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ggfwyekm0-java-quarkus-gitops